[workspace]
default-members = [
  "betrusted-boot",
]
members = [
  "svd2utra",
  "xtask",
  "betrusted-boot",
]
resolver = "2"

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = "fat"
#panic = "abort" # Remove panic output, which can reduce file size
#opt-level = 'z'  # Optimize for size instead of performance
