[package]
name = "betrusted-boot"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"

[dependencies]
utralib = {path = "../utralib"}

[dependencies.curve25519-dalek]
version = "3.1.0" # note this is patched to our fork in ./Cargo.toml
default-features = false
features = ["u32_backend"]

[dependencies.ed25519-dalek]
version="1.0.1"
default-features = false

[features]
debug-print = []
small-soc = []
default = ["debug-print", "small-soc"]
# default = []

[target.'cfg(not(any(windows, unix)))'.dependencies]
utralib = { path = "../utralib"}
